name: menu
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dot_navigation_bar: ^1.0.1+4
  flutter_svg: ^0.22.0
  image_picker: ^0.8.7+5
  provider: ^6.0.5
  permission_handler: ^10.2.0
  custom_navigation_bar: ^0.8.2
  flutter_native_splash: ^2.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  android: true
  ios: true
  web: false
  image: assets/logo/main-blue-logo.png
  color: "#FFFFFF"
  fill: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: center

  android_12:
    image: assets/logo/main-blue-logo.png
    color: "#FFFFFF"
    fill: true
    fullscreen: true
    android_gravity: center
    ios_content_mode: center

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/
    - assets/test/

  fonts:
    - family: Font
      fonts:
        - asset: assets/font/Font.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
